name: GrapesJS Qualty Checks
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  quailty-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
      - name: Line
        run: pnpm lint
      - name: Format
        run: pnpm format:check
      - name: Build
        run: pnpm build --force
      - name: Test
        run: pnpm test
      - name: Docs
        run: pnpm docs:api
